name: Detect Secrets
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  secrets-scan:
    uses: probely/snyk-prodsec/.github/workflows/secrets-scanning.yml@main
    with:
      channel: probely-alerts
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_SECRET }}
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
